on:
  push:
    branches: [ 'feature/netcore' ]

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  PACKAGE_VERSION: '6.0.0'

jobs:
  build:
    runs-on: 'windows-2022'

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore package
      run: nuget restore Xbim.Geometry.Engine.sln -NonInteractive

    - name: Restore package
      run: nuget restore Xbim.Geometry.Engine\packages.config -NonInteractive -PackagesDirectory .\packages

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build app for release
      run: msbuild Xbim.Geometry.Engine.sln /t:build /p:platform='Any CPU' /p:Configuration=Release

    - name: Move nugets to output
      run: mkdir ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: Move nugets to output
      run: Get-ChildItem -Path .\packages\ -Filter *.nupkg -Recurse | % {copy-item -Path $_ -Destination ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -Force -Container }

    - name: Move nugets to output
      run: Get-ChildItem -Path .\Xbim.Geometry\ -Filter *.nupkg -Recurse | % {copy-item -Path $_ -Destination ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -Force -Container }

    - name: Move nugets to output
      run: Get-ChildItem -Path .\Xbim.Geometry.Engine.Interop\ -Filter *.nupkg -Recurse | % {copy-item -Path $_ -Destination ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -Force -Container }

    - name: Move nugets to output
      run: Get-ChildItem -Path .\Xbim.ModelGeometry.Scene\ -Filter *.nupkg -Recurse | % {copy-item -Path $_ -Destination ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -Force -Container }

    - name: Upload artifact package
      uses: actions/upload-artifact@v3
      with:
        name: Package artifact
        path: ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
